version: '2'

volumes:
  jenkins-home:
    driver: local

services:
  jenkins:
    image: jenkins:2.0
    volumes:
      - jenkins-home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
