---
- name: update user-sessions
  sudo: yes
  yum: name=user-sessions state=latest
  tags:
    - user-sessions

- name: configure user-sessions
  sudo: yes
  template: src=user-sessions.properties.j2 dest=/etc/iplant/de/user-sessions.properties owner=root group=root mode=0644
  notify:
    - restart user-sessions
  tags:
    - user-sessions

- name: Copy the /etc/iplant/de/supervisord/user-sessions.ini file
  sudo: yes
  copy: src=user-sessions.ini dest=/etc/iplant/de/supervisord/ owner=root group=root mode=0644
  notify:
    - restart user-sessions
  tags:
    - user-sessions

- name: user-sessions is present in supervisord
  sudo: yes
  supervisorctl: name=user-sessions state=present
  tags:
    - user-sessions

- name: user-sessions is running
  sudo: yes
  supervisorctl: name=user-sessions state=started
  tags:
    - user-sessions
