---
- name: install nagios packages
  with_items: packages
  action: "{{ packager }} name={{ item }} state=latest"
  register: install

- name: install check_connections
  copy: src=check_connections dest={{ plugin_dir }}/check_connections mode=0755

- name: place config file
  template: src=nrpe.cfg.j2 dest=/etc/nagios/nrpe.cfg
  register: cfg

- name: place custom service checks
  with_items: nrpe_check_services|default([])
  template: src=check_service.cfg.j2 dest={{ cfg_include_dir }}/check_{{ item }}.cfg
  register: custom

- when: restarts_tomcat|default(false)
  include: install-tomcat-handler.yaml

- name: remove defunct files
  file: path={{item}} state=absent
  with_items:
    - "{{cfg_include_dir}}/restart-iplantosm.cfg"
    - "{{eventhandler_dir}}/restart-iplantosm.sh"
    - "{{eventhandler_dir}}/eventhandler-iplantosm.sh"

- name: enable nrpe
  service: name={{ service }} enabled=yes

- name: restart nrpe
  when: install|changed or cfg|changed or custom|changed or tomcat|changed
  service: name={{ service }} state=restarted
# This can't be done asynchronously because it causes ansible-playbook 1.7 to crash
  # async: 45
  # poll: 0  
