---
- name: update infosquito
  sudo: yes
  yum: name=infosquito state=latest
  tags:
    - infosquito

- name: configure infosquito
  sudo: yes
  template: src=infosquito.properties.j2 dest=/etc/iplant/de/infosquito.properties owner=root group=root mode=0644
  notify:
    - restart infosquito
  tags:
    - infosquito

- name: Copy the /etc/iplant/de/supervisord/infosquito.ini file
  sudo: yes
  copy: src=infosquito.ini dest=/etc/iplant/de/supervisord/ owner=root group=root mode=0644
  notify:
    - restart infosquito
  tags:
    - infosquito

- name: infosquito is present in supervisord
  sudo: yes
  supervisorctl: name=infosquito state=present
  tags:
    - infosquito

- name: infosquito is running
  sudo: yes
  supervisorctl: name=infosquito state=started
  tags:
    - infosquito
