---
- name: stop jex-events
  sudo: yes
  supervisorctl: name=jex-events state=stopped
  tags:
    - jex-events

- name: update jex-events
  sudo: yes
  yum: name=jex-events state=latest
  tags:
    - jex-events

- name: configure jex-events
  sudo: yes
  template: src=jex-events.properties.j2 dest=/etc/iplant/de/jex-events.properties owner=root group=root mode=0644
  notify:
    - restart jex-events
  tags:
    - jex-events

- name: Copy the /etc/iplant/de/supervisord/jex-events.ini file
  sudo: yes
  copy: src=jex_events.ini dest=/etc/iplant/de/supervisord/ owner=root group=root mode=0644
  notify:
    - restart jex-events
  tags:
    - jex-events

- name: jex-events is present in supervisord
  sudo: yes
  supervisorctl: name=jex-events state=present
  tags:
    - jex-events

- name: jex-events is running
  sudo: yes
  supervisorctl: name=jex-events state=started
  tags:
    - jex-events
