---
- name: install denyhosts package
  action: "{{ packager }} name=denyhosts state=latest"
  register: install

- name: place config file
  copy: src=denyhosts.conf dest=/etc/denyhosts.conf mode=0600
  register: cfg

- name: place allowed-hosts
  template: src=allowed-hosts.j2 dest=/var/lib/denyhosts/allowed-hosts
  register: allowed

- name: enable on boot
  when: install|changed
  service: name=denyhosts enabled=true

- name: restart denyhosts
  when: install|changed or cfg|changed or allowed|changed
  service: name=denyhosts state=restarted

