---
- name: create drop directory
  file: path={{drop_dir}} mode=2775 state=directory

- name: initialize git repository for drop
  command: chdir={{drop_dir}} git init --shared=group

- debug: msg="transferring {{de_war_url}}"
- name: transfer de.war
  get_url: dest={{drop_dir}} url={{de_war_url}} mode=0664 force=True

- debug: msg="transferring {{bg_war_url}}"
- name: transfer belphegor.war
  get_url: dest={{drop_dir}} url={{bg_war_url}} mode=0664 force=True

- debug: msg="transferring {{scm_tgz_url}}"
- name: transfer scm.tar.gz
  get_url: dest={{drop_dir}} url={{scm_tgz_url}} mode=0664 force=True

- debug: msg="transferring {{clavin_tgz_url}}"
- name: transfer clavin.tar.gz
  get_url: dest={{drop_dir}} url={{clavin_tgz_url}} mode=0664 force=True

- debug: msg="transferring {{de_db_tgz_url}}"
- name: transfer database.tar.gz
  get_url: dest={{drop_dir}} url={{de_db_tgz_url}} mode=0664 force=True

- debug: msg="transferring {{notification_db_tgz_url}}"
- name: transfer notification-db.tar.gz
  get_url: dest={{drop_dir}} url={{notification_db_tgz_url}} mode=0664 force=True

- debug: msg="transferring {{metadata_db_tgz_url}}"
- name: transfer metadata-db.tar.gz
  get_url: dest={{drop_dir}} url={{metadata_db_tgz_url}} mode=0664 force=True

- debug: msg="transferring {{jex_db_tgz_url}}"
- name: transfer jex-db.tar.gz
  get_url: dest={{drop_dir}} url={{jex_db_tgz_url}} mode=0664 force=True

- debug: msg="transferring {{facepalm_tgz_url}}"
- name: transfer facepalm.tar.gz
  get_url: dest={{drop_dir}} url={{facepalm_tgz_url}} mode=0664 force=True

- name: generate drop manifest
  command: chdir={{drop_dir}} /usr/local/bin/generate-manifest.clj
    -d {{drop_name}} -v {{de_version}}

- name: set drop manifest permissions
  file: path={{drop_dir}}/manifest.json mode=0664

- name: stage drop directory to git
  command: chdir={{drop_dir}} git add .

- name: commit staged changes
  command: chdir={{drop_dir}} git commit -m 'initial commit - generated by ansible'

- name: create latest link
  file: path={{drop_dir_base}}/latest state=link src={{drop_name}} force=True
