---
- name: update info-typer
  sudo: yes
  yum: name=info-typer state=latest
  tags:
    - info-typer

- name: configure info-typer
  sudo: yes
  template: src=info-typer.properties.j2 dest=/etc/iplant/de/info-typer.properties owner=root group=root mode=0644
  notify:
    - restart info-typer
  tags:
    - info-typer

- name: Copy the /etc/iplant/de/supervisord/info-typer.ini file
  sudo: yes
  copy: src=info-typer.ini dest=/etc/iplant/de/supervisord/ owner=root group=root mode=0644
  notify:
    - restart info-typer
  tags:
    - info-typer

- name: info-typer is present in supervisord
  sudo: yes
  supervisorctl: name=info-typer state=present
  tags:
    - info-typer

- name: info-typer is running
  sudo: yes
  supervisorctl: name=info-typer state=started
  tags:
    - info-typer
