---
- name: stop condor-log-monitor
  sudo: yes
  supervisorctl: name=clm state=stopped
  tags:
    - condor-log-monitor

- name: update condor-log-monitor
  yum: name=condor-log-monitor state=latest
  tags:
    - condor-log-monitor

- name: configure condor-log-monitor
  sudo: yes
  template: src=condor_log_monitor.properties.j2 dest=/etc/iplant/de/condor_log_monitor.properties owner=root group=root mode=0644
  notify:
    - restart condor-log-monitor
  tags:
    - condor-log-monitor

- name: copy the /etc/iplant/de/supervisord/condor_log_monitor.ini file
  sudo: yes
  copy: src=condor_log_monitor.ini dest=/etc/iplant/de/supervisord/ owner=root group=root mode=0644
  notify:
    - restart condor-log-monitor
  tags:
    - condor-log-monitor

- name: condor-log-monitor is present in supervisord
  sudo: yes
  supervisorctl: name=clm state=present
  tags:
    - condor-log-monitor

- name: condor-log-monitor is running
  sudo: yes
  supervisorctl: name=clm state=started
  tags:
    - condor-log-monitor
