---
- name: update saved-searches
  sudo: yes
  yum: name=saved-searches state=latest
  tags:
    - saved-searches

- name: configure saved-searches
  sudo: yes
  template: src=saved-searches.properties.j2 dest=/etc/iplant/de/saved-searches.properties owner=root group=root mode=0644
  notify:
    - restart saved-searches
  tags:
    - saved-searches

- name: Copy the /etc/iplant/de/supervisord/saved-searches.ini file
  sudo: yes
  copy: src=saved-searches.ini dest=/etc/iplant/de/supervisord/ owner=root group=root mode=0644
  notify:
    - restart saved-searches
  tags:
    - saved-searches

- name: saved-searches is present in supervisord
  sudo: yes
  supervisorctl: name=saved-searches state=present
  tags:
    - saved-searches

- name: saved-searches is running
  sudo: yes
  supervisorctl: name=saved-searches state=started
  tags:
    - saved-searches
